sudo: required
language: node_js
services:
  - docker

before_install:
  - docker build -t gharaszti/docker-react -f Dockerfile.dev .

scripts:
  - docker run gharaszti/docker-react npm run test -- --coverage